<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>05bec00f-7f2a-4dde-a80c-c22069d3ab37</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Auth\Auth.csproj" />
  </ItemGroup>

</Project>
